version: '3.7'

services:
  landing-page:
    build:
      context: .  # Build the HTML page from the Dockerfile in the current directory
    networks:
      - web-network
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf # Mount the custom NGINX config
    expose:
      - "5007"
      - "5008"
      - "5009"    # Expose port 80 for the NGINX load balancer to access
    deploy:
      replicas: 3 
  nginx:
    image: nginx:alpine  # Use the official NGINX image
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the custom NGINX config
    ports:
      - "5001:5001"  # Expose port 5003 on the host, forwarding to port 5003 on the container
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
