version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/usr/share/nginx/html
    container_name: sample1
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
